### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by hehehehaa** [xeondev1337/RoyaleBrawl#12]
idk how to fix this

![image](https://user-images.githubusercontent.com/110904928/184130610-bb82eca0-c882-45a5-acd4-1411aad7a605.png)

**Comment by hehehehaa** [comment]
![2022-08-11 131421](https://user-images.githubusercontent.com/110904928/184131070-f82c178b-b8bf-4b73-a9cb-ff28345cb919.png)

**Comment by hehehehaa** [comment]
i think the problem is in config.json

**Comment by hehehehaa** [comment]
**COMMON SOMEONE HELP ME**

**Comment by hehehehaa** [comment]
why is everyone dead.

**Comment by hehehehaa** [comment]
j

**Comment by MCausc78** [comment]
Are you created database?
