### ISSUE TITLE
Исправление!

### ISSUE THREAD

**Issue by MusyaBrawl** [xeondev1337/RoyaleBrawl#14]
В Character.cs в функции TickHeals() присутствует одна вещь, которая не соответствует коду из libg.so:
...
            int heal = m_maxHitpoints / 6;
...
Вот фрагмент из функции LogicCharacterServer::getRegeneratePerSecond:
...
    {
      return 13 * *(_DWORD *)(a1 + 148) / 100;
    }
...
Поэтому прошу исправить на:
*** int heal = 13 * m_maxHitpoints / 100; ***
Удачи!🦼

**Comment by XidMods05** [comment]
> 

Ты еблан?

**Comment by xeondev1337** [comment]
чел, харош. но мог бы pull request сделать. а так да, я даже щяс сам посмотрел, и это правильный код, а (this+148) это maxHitpoints, щяс будет обновление

**Comment by xeondev1337** [comment]
исправлено в коммите a937f16f4a86b76ad67c407d34b2816ddb3b89fe
