### ISSUE TITLE
Виснет на 100% после подбора игроков 

### ISSUE THREAD

**Issue by diedside666** [xeondev1337/RoyaleBrawl#18]
Крч всё робит, нажимаешь играть, идёт подбор игроков 1 из 6. Идёт обратный отсчёт, затем заставка бравла с прогресс баром на 100% и всё. В консоли только Ignoring message of unknown type 10111 Ignoring message of unknown type 10113.
![182920651-0061d7dd-b6db-42f5-947b-1e0784bd21ac](https://user-images.githubusercontent.com/113336089/189597084-ecbe9a98-7c26-4668-a946-7ea0098a5305.jpg)

**Comment by xeondev1337** [comment]
это для кого написано.
![image](https://user-images.githubusercontent.com/49839864/200111526-3fab1685-78f2-4b63-bf97-cace7cf69571.png)
